### ISSUE TITLE
about speed

### ISSUE THREAD

**Issue by ZIKO94ZIKO** [ronitsinha/speed-detector#2]
hi sir , i hope you are doing well , i try you program by my camera ip ,its work but i have a question about some parameter , 
what is : 
1/the distance between the camera and the vehicle 
2/ FOV and anglle of view , and FPS 
3/ altitude between the camera and read

**Comment by ronitsinha** [comment]
These are all values you would need to find on your own. Anyway, the only parameter this program would ever need is the distance of the road in the camera. You can use the those other values to [calculate that distance](https://www.pyimagesearch.com/2015/01/19/find-distance-camera-objectmarker-using-python-opencv/).
