### ISSUE TITLE
(yolov4) PS C:\Users\Administrator\Downloads\Compressed\speed-detector-master> python main.py Traceback (most recent call last):   File "main.py", line 14, in <module>     raise Exception("No road specified.") Exception: No road specified.

### ISSUE THREAD

**Issue by byq-luo** [ronitsinha/speed-detector#4]
(yolov4) PS C:\Users\Administrator\Downloads\Compressed\speed-detector-master> python main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    raise Exception("No road specified.")
Exception: No road specified.

**Comment by aditisingh2362** [comment]
Give a road name in your argument

**Comment by byq-luo** [comment]
Thanks.
