### ISSUE TITLE
OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): http://192.168.2.3:8081/video in function 'cv::icvExtractPattern'   Frame capture failed, stopping... Closing video capture... Done.

### ISSUE THREAD

**Issue by byq-luo** [ronitsinha/speed-detector#5]
OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): http://192.168.2.3:8081/video in function 'cv::icvExtractPattern'

Frame capture failed, stopping...
Closing video capture...
Done.

**Comment by ronitsinha** [comment]
It looks like OpenCV can't find the video at that IP. Make sure that the video source is working and is compatible with OpenCV's VideoCapture
